<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jhe_websitetemplate"
 *
 * Auto generated by Extension Builder 2017-01-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'JHE Website Template',
	'description' => '',
	'category' => 'templates',
	'author' => 'Jari-Hermann Ernst, M.A.',
	'author_email' => 'jari-hermann.ernst@t-online.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);